spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  security:
    user: ${APP_SECURITY_USERNAME}
    password: ${APP_SECURITY_PASSWORD}
    roles: MEMBER_ADMIN,ACTUATOR

  jpa:
    show-sql: false

management:
  endpoint:
    health:
      show-details: never

  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0.1}

  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:}

logging:
  level:
    root: INFO
    com.bcbs.member.service: INFO

server:
  tomcat:
    connection-timeout: ${SERVER_CONNECTION_TIMEOUT:5s}
